### PR TITLE
Person class #23

### PR DESCRIPTION
**Pull request by eugene-choi**
Please review my pull request for person.js and unit.person.js. Thanks!

### CODE REVIEW

**Review by Ulbert — CHANGES_REQUESTED** [review]
Your pull request would delete chores.test.js. Pull or rebase from master and try again.

**Comment by eugene-choi** [comment]
I just rebased from master. Hope this is fine.

**Comment by Ulbert** [comment]
Your branch still doesn’t have chores.test.js. I think you need to pull from master.

**Comment by eugene-choi** [comment]
thanks. I added the test.js file

**Review by Ulbert — APPROVED** [review]

**Pull request merged**
